### ISSUE TITLE
TypeError: Cannot read property 'appname' of undefined

### ISSUE THREAD

**Issue by rakshitmidha** [Qolzam/firestore-social-backend#1]
TypeError: Cannot read property 'appname' of undefined

**Comment by Qolzam** [comment]
Thanks for reposting. Are you sure that you set `config variables` for firebase :
1. Set the `gmail.email` and `gmail.password` Google Cloud environment variables to match the email and password of the Gmail account used to send emails (or [the app password](https://support.google.com/accounts/answer/185833?hl=en) if your account has 2-step verification enabled). The `recaptcha.secretKey` key is using for recaptcha secret key in SMS verification. The `phone.sourceNumber`, `plivo.authId` and `plivo.authToken` are configuration from [Plivo SMS Service](https://www.plivo.com/) in SMS verification .For this use:
    ```bash
    firebase functions:config:set gmail.email="myusername@gmail.com" gmail.password="secretpassword" recaptcha.secretkey="secretKey" phone.sourcenumber="sourceNumber" plivo.authid="authId" plivo.authtoken="authToken" setting.appname="App Name"
    ```

**Comment by evan9523** [comment]
I am facing the same issue

**Comment by evan9523** [comment]
Please help Please

**Comment by Qolzam** [comment]
@evan9523 be sure you set the firebase config environment variables. https://github.com/Qolzam/firestore-social-backend/issues/1#issuecomment-397847977
