### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by TylerJKing** [Qolzam/firestore-social-backend#9]
I followed the steps listed in the medium article, but when I run 'npm start' for this portion of the guide, I get the following:

Starting type checking service...
Using 1 worker with 2048MB memory limit
Hash: ebbae49c4c1b3cbcbce2
Version: webpack 4.30.0
Time: 10033ms
Built at: 04/14/2019 2:07:58 AM
 1 asset
Entrypoint main = index.js
 [0] external "firebase-functions" 42 bytes {0} [built]
 [1] ./src/data/index.ts 210 bytes {0} [built]
 [2] ./src/domain/common/index.ts 328 bytes {0} [built]
 [3] external "express" 42 bytes {0} [built]
 [4] ./src/data/httpStatusCode.ts 3.86 KiB {0} [built]
 [5] external "moment" 42 bytes {0} [built]
 [6] external "body-parser" 42 bytes {0} [built]
 [7] external "request" 42 bytes {0} [built]
 [8] external "cookie-parser" 42 bytes {0} [built]
[13] ./src/index.ts 916 bytes {0} [built]
[14] ./src/services/authorize/authorizeService.ts 12.4 KiB {0} [built]
[21] ./src/services/authorize/publicAuthService.ts 11.3 KiB {0} [built]
[23] ./src/services/users/userService.ts 6.08 KiB {0} [built]
[24] ./src/services/common/mailService.ts 1.19 KiB {0} [built]
[25] ./src/services/comments/commentService.ts 3.11 KiB {0} [built]
    + 12 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/services/authorize/authorizeService.ts
Module not found: Error: Can't resolve '../../domain/authorize/verification' in '/home/tking/work/src/github.com/TylerJKing/firestore-social-backend/functions/src/services/authorize'
 @ ./src/services/authorize/authorizeService.ts 18:23-69
 @ ./src/index.ts

ERROR in ./src/services/authorize/publicAuthService.ts
Module not found: Error: Can't resolve '../../domain/authorize/verification' in '/home/tking/work/src/github.com/TylerJKing/firestore-social-backend/functions/src/services/authorize'
 @ ./src/services/authorize/publicAuthService.ts 17:23-69
 @ ./src/index.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tking/.npm/_logs/2019-04-14T06_07_58_855Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! functions@ start: `npm run build && firebase deploy`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tking/.npm/_logs/2019-04-14T06_07_58_904Z-debug.log

**Comment by Qolzam** [comment]
Please change **Verification** file name in __domain/authorize__ to **verification** **(V -> v)** and check again.

**Comment by TylerJKing** [comment]
Thanks!
Fixed. There was also an issue with domain/circles/index.ts importing "userTie" where the case was set to "UserTie" that I had to fix.
